[package]
name = "rusty-physics"
version = "0.1.0"
edition = "2024"

[dependencies]
avian3d = "0.4.1"
bevy = "^0.17"
bevy_asset = "^0.17"
bevy_egui = "^0.38"
serde = {version = "^1.0", features = ["derive"]}
serde_json = "^1.0"
