[package]
name = "rusty-physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "^0.16"
bevy_asset = "^0.16"
bevy_egui = "0.36"
bevy_rapier3d = { version = "0.30", features = [ "simd-stable", "debug-render-3d" ] }
